apiVersion: v1
kind: ConfigMap
metadata:
  name: core-api-config
data:
  DB_HOST: "hive-rds.cl84s6yy4jm6.us-west-2.rds.amazonaws.com"
  DB_USER: "admin"
  DB_PASSWORD: "Cloud123"
  DB_NAME: "streamhive"
  MAIL_SERVER: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USERNAME: "shubhamndeshmukh02@gmil.com"
  MAIL_PASSWORD: "xdvp nicm keqh yrbm"
  PORT: "5000"
