apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-deployment
  labels:
    app: music
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
        - name: music-container
          image: 637423282941.dkr.ecr.us-west-2.amazonaws.com/streamhive-music:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: music-service
spec:
  selector:
    app: music
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
