apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaming-deployment
  labels:
    app: gaming
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gaming
  template:
    metadata:
      labels:
        app: gaming
    spec:
      containers:
        - name: gaming-container
          image: 891376951737.dkr.ecr.us-west-2.amazonaws.com/streamhive-gaming:8efb49f94f771d36a853bb73a8f0d56bb9b06b00
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: gaming-service
spec:
  selector:
    app: gaming
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
