apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery-deployment
  labels:
    app: food-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-delivery
  template:
    metadata:
      labels:
        app: food-delivery
    spec:
      containers:
        - name: food-delivery-container
          image: 637423282941.dkr.ecr.us-west-2.amazonaws.com/streamhive-food-delivery:a328ef635b908eab0c66fe5c79a3168c07760782
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: food-delivery-service
spec:
  selector:
    app: food-delivery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
