apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamwallet-deployment
  labels:
    app: streamwallet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamwallet
  template:
    metadata:
      labels:
        app: streamwallet
    spec:
      containers:
        - name: streamwallet-container
          image: 891376951737.dkr.ecr.us-west-2.amazonaws.com/streamhive-streamwallet:93edd8ecf954eb118bb602098fda5d383480ed00
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: streamwallet-service
spec:
  selector:
    app: streamwallet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
