apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamwallet-deployment
  labels:
    app: streamwallet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamwallet
  template:
    metadata:
      labels:
        app: streamwallet
    spec:
      containers:
        - name: streamwallet-container
          image: 637423282941.dkr.ecr.us-west-2.amazonaws.com/streamhive-streamwallet:a328ef635b908eab0c66fe5c79a3168c07760782
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: streamwallet-service
spec:
  selector:
    app: streamwallet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
